/** Lista de emojis com palavras-chave para busca */
export const EMOJI_LIST: { emoji: string; keywords: string[] }[] = [
  { emoji: '😀', keywords: ['feliz', 'sorriso', 'happy', 'smile'] },
  { emoji: '😊', keywords: ['feliz', 'sorrindo', 'blush'] },
  { emoji: '👍', keywords: ['ok', 'joinha', 'like', 'bom'] },
  { emoji: '👎', keywords: ['não', 'thumbs down'] },
  { emoji: '✅', keywords: ['certo', 'check', 'confirmado', 'sim'] },
  { emoji: '❌', keywords: ['errado', 'x', 'não', 'negativo'] },
  { emoji: '🎪', keywords: ['feira', 'tenda', 'circo', 'evento'] },
  { emoji: '📦', keywords: ['caixa', 'encomenda', 'pacote'] },
  { emoji: '📱', keywords: ['celular', 'telefone', 'rede social'] },
  { emoji: '🛒', keywords: ['carrinho', 'mercado', 'compras'] },
  { emoji: '🚀', keywords: ['crescimento', 'vendas', 'sucesso'] },
  { emoji: '💬', keywords: ['mensagem', 'chat', 'comunicação'] },
  { emoji: '📈', keywords: ['gráfico', 'crescimento', 'financeiro'] },
  { emoji: '🏷️', keywords: ['preço', 'precificação', 'etiqueta'] },
  { emoji: '💪', keywords: ['força', 'empreendedorismo', 'determinação'] },
  { emoji: '🌱', keywords: ['início', 'começando', 'novo'] },
  { emoji: '🌿', keywords: ['crescimento', 'evolução'] },
  { emoji: '🌳', keywords: ['experiência', 'árvore'] },
  { emoji: '👑', keywords: ['mestre', 'líder', 'rei'] },
  { emoji: '🤷‍♀️', keywords: ['cliente', 'dúvida'] },
  { emoji: '📉', keywords: ['preço baixo', 'queda'] },
  { emoji: '🤫', keywords: ['divulgação', 'segredo'] },
  { emoji: '🧾', keywords: ['financeiro', 'nota', 'organização'] },
  { emoji: '🏦', keywords: ['banco', 'crédito'] },
  { emoji: '🚚', keywords: ['transporte', 'entrega'] },
  { emoji: '💰', keywords: ['dinheiro', 'renda'] },
  { emoji: '🌟', keywords: ['estrela', 'destaque'] },
  { emoji: '⭐', keywords: ['estrela', 'favorito'] },
  { emoji: '💡', keywords: ['ideia', 'luz', 'inspiração'] },
  { emoji: '🔥', keywords: ['fogo', 'quente', 'popular'] },
  { emoji: '❤️', keywords: ['amor', 'coração'] },
  { emoji: '🙌', keywords: ['celebração', 'mãos'] },
  { emoji: '🤝', keywords: ['parceria', 'acordo'] },
  { emoji: '📋', keywords: ['lista', 'checklist'] },
  { emoji: '🛍️', keywords: ['compras', 'loja'] },
  { emoji: '🏠', keywords: ['casa', 'lar'] },
  { emoji: '🌍', keywords: ['mundo', 'global'] },
  { emoji: '🎯', keywords: ['objetivo', 'meta', 'alvo'] },
  { emoji: '✏️', keywords: ['editar', 'escrever'] },
  { emoji: '🔔', keywords: ['notificação', 'alerta'] },
  { emoji: '📅', keywords: ['data', 'calendário'] },
  { emoji: '⏰', keywords: ['tempo', 'hora'] },
  { emoji: '🌸', keywords: ['flor', 'beleza'] },
  { emoji: '🌻', keywords: ['girassol', 'natureza'] },
  { emoji: '🍎', keywords: ['maçã', 'fruta', 'alimento'] },
  { emoji: '🥕', keywords: ['legume', 'hortaliça'] },
  { emoji: '🛠️', keywords: ['ferramenta', 'trabalho'] },
  { emoji: '⚡', keywords: ['rápido', 'energia'] },
  { emoji: '🎉', keywords: ['celebração', 'festa'] },
  { emoji: '🏆', keywords: ['troféu', 'vitória'] },
  { emoji: '💼', keywords: ['trabalho', 'negócio'] },
  { emoji: '📊', keywords: ['gráfico', 'dados'] },
  { emoji: '🔒', keywords: ['seguro', 'proteção'] },
  { emoji: '🔓', keywords: ['aberto', 'acesso'] },
  { emoji: '✌️', keywords: ['paz', 'vitória'] },
  { emoji: '🙏', keywords: ['obrigado', 'rezar'] },
  { emoji: '👀', keywords: ['ver', 'observar'] },
  { emoji: '🤔', keywords: ['pensar', 'dúvida'] },
  { emoji: '😊', keywords: ['feliz'] },
  { emoji: '🙂', keywords: ['neutro', 'simples'] },
  { emoji: '😢', keywords: ['triste', 'dificuldade'] },
  { emoji: '💻', keywords: ['computador', 'tecnologia'] },
  { emoji: '🖼️', keywords: ['imagem', 'foto'] },
  { emoji: '📷', keywords: ['câmera', 'foto'] },
  { emoji: '🎨', keywords: ['arte', 'criativo'] },
  { emoji: '✂️', keywords: ['cortar', 'artesanato'] },
  { emoji: '🧵', keywords: ['costura', 'linha'] },
  { emoji: '🪡', keywords: ['agulha', 'costura'] },
  { emoji: '🧺', keywords: ['cesta', 'feira'] },
  { emoji: '🍞', keywords: ['pão', 'alimento'] },
  { emoji: '🧀', keywords: ['queijo', 'laticínio'] },
  { emoji: '🍯', keywords: ['mel', 'doce'] },
  { emoji: '🌶️', keywords: ['pimenta', 'tempero'] },
  { emoji: '🥬', keywords: ['verdura', 'hortaliça'] },
  { emoji: '🍊', keywords: ['laranja', 'fruta'] },
  { emoji: '🍇', keywords: ['uva', 'fruta'] },
  { emoji: '🛡️', keywords: ['proteção', 'segurança'] },
  { emoji: '🔑', keywords: ['chave', 'acesso'] },
  { emoji: '📌', keywords: ['fixar', 'importante'] },
];
